env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules: 
  '@typescript-eslint/no-explicit-any': off
  'no-fallthrough': warn
  '@typescript-eslint/no-inferrable-types': off
  # prettier/prettier: 'warn

